### ISSUE TITLE
PDBML SEQRES equivalent code fails with residue numbers below 1

### ISSUE THREAD

**Issue by AndrewCRMartin** [ACRMGroup/bioplib#12]
Try

         pdb2pir -s 1yqv.xml

Output for the light chain is

        mdIVLTQSPAIMSASPGEKVTMTCSASSSV

but the sequence is the same in the SEQRES and ATOM records (Met Asp Ile)
I believe this is because the first residue is number 0 instead of 1

**Comment by CraigPorter** [comment]
The pdbml parser was setting the first residue number to 1 instead of 0 for 1yqv. 

The pdbml parser sets the residue number from label_seq_id if auth_seq_id is not set. I've changed the parser function to set a flag if the author's sequence number has been used instead of checking if resnum == 0. 

pdb2pir gives the correct output for 1yqv.xml

**Comment by AndrewCRMartin** [comment]
Wonderful! I've got code working to read the biological units from PDB
files (still needs some tidying up) - the format is quite complicated. I
suspect we won't get that into PDBML yet...

A.


On Thu, Jun 25, 2015 at 5:20 PM, CraigPorter <notifications@github.com>
wrote:

>  The pdbml parser was setting the first residue number to 1 instead of 0
> for 1yqv.
>
> The pdbml parser sets the residue number from label_seq_id if auth_seq_id
> is not set. I've changed the parser function to set a flag if the author's
> sequence number has been used instead of checking if resnum == 0.
>
> pdb2pir gives the correct output for 1yqv.xml
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ACRMGroup/bioplib/issues/12#issuecomment-115308227>.
>



-- 
Dr. Andrew C.R. Marin,
Reader in Bioinformatics and Computational Biology.
Institute of Structural and Molecular Biology, UCL
http://www.bioinf.org.uk/  Twitter: @DrAndrewMartin

**Comment by AndrewCRMartin** [comment]
I assume this also works for residue numbers <0 ???

**Comment by CraigPorter** [comment]
Yes, I put in unit tests where the author's residue number was: -1, 0 and 1. Also a test where the number was absent.
