### ISSUE TITLE
Possible bug with profiit

### ISSUE THREAD

**Issue by ocstx** [ACRMGroup/bioplib#19]
This is not related to bioptools, but to profit. However since I did not find a place to report bugs to profit I write it here. If you do not consider this correct, could you please point me in the right direction for reporting a posible bug in profit?

I just realized that after executing RATOM (any atom or * here) after executing ALLVSALL in my set of pdbs (5) I get:
Segmentation fault (core dumped)
I tested that in Profit3.1 in both Linux an Mac (Big Sur) and in Profit3.3 in Linux precompiled binary and a binary compiled by me.
Perhaps RATOMS is not supposed to be executed after ALLVSALL (A pity) but I believe that a Segmentation fault (Core dumped) should not be the result.
Thank you very much.

**Comment by AndrewCRMartin** [comment]
@ocstx Thank you! I have noted this in the ProFit github issues and will look into it ASAP.

Andrew
