### ISSUE TITLE
PDBML header reading needs to include MODRES records

### ISSUE THREAD

**Issue by AndrewCRMartin** [ACRMGroup/bioplib#8]
The PDBML reader should be picking up the equivalent of MODRES and reconstructing the PDB style MODRES records in the WPDB->header stringlist
I am assuming that this doesn't work at the moment through experience with SEQRES. If this is (as I suspect) the case it would break "pdb2pir -s"

**Comment by CraigPorter** [comment]
The pdbml reader is now adding MODRES records to the WPDB->header stringlist.

pdb2pir -s is now setting the correct residue for modified residues. (See 1CTP.xml for an example.)

**Comment by AndrewCRMartin** [comment]
Excellent! Does this mean we are now there with the changes to get all the
tools working with PDBML and PDB files?
A.


On Wed, Jun 24, 2015 at 4:31 PM, CraigPorter <notifications@github.com>
wrote:

>  Closed #8 <https://github.com/ACRMGroup/bioplib/issues/8>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ACRMGroup/bioplib/issues/8#event-339073803>.
>



-- 
Dr. Andrew C.R. Marin,
Reader in Bioinformatics and Computational Biology.
Institute of Structural and Molecular Biology, UCL
http://www.bioinf.org.uk/  Twitter: @DrAndrewMartin

**Comment by CraigPorter** [comment]
I think so... Anything involving transforming coordinates, getting chains, getting ranges, stripping/adding hydrogens, renumbering and counting atoms should work. We've just dealt with pdbheader and pdb2pir. I'm not au fait with all 42 bioptools in the directory but I think that covers everything.

I'll run through the bioptools and check that they're outputting sensible results.
